project:
  type: book

book:
  title: "Cryptography Challenge"
  author: "The Alan Turing Institute"
  date: "2023-05-02"
  chapters:
    - index.qmd
    - ciphers_vs_codes.qmd
    - part: symmetric.qmd
      chapters:
        - caesar.qmd
        - monosub.qmd
        - vigenere.qmd
        - modular1.qmd
    - part: asymmetric.qmd
      chapters:
        - rsa1.qmd
        - modular2.qmd
        - rsa2.qmd

bibliography: references.bib

format:
  html:
    theme: flatly
    css: styles.css
    include-in-header:
        - text: |
            <script src="https://cdn.plot.ly/plotly-2.20.0.min.js" charset="utf-8"></script>
  pdf:
    documentclass: scrreprt

execute:
    echo: false
