# Cryptography Game Resources

<script type="text/javascript">
{{< include rsa_shared.js >}}
{{< include rsa2_shared.js >}}
</script>
<script type="module">
{{< include game_resources.js >}}
</script>
<script type="module">
{{< include caesar.js >}}
</script>
<script type="module">
{{< include samples.js >}}
{{< include monosub_freq.js >}}
{{< include monosub_encode.js >}}
</script>


The goal of the game is to design a cryptographic protocol for communication between your
encryption and decryption teams, communicating solely via the ‘public-channel’. Scoring a point
for each successfully transmitted message, and taking a point away from your rival team for each
message your hackers can decipher.

## RULES

1. All communication with you corresponding teams must be via the public channel.
2. If using RSA for encryption no $n=pq$ greater than 500!
3. Any message can be sent via the public channel, but only those from the list of approved messages will score!

## Asymetric Encryption Tools (RSA)

Steps for implementing an RSA encryption scheme:

### Key Gen (by recipient)

The goal is to compute a triple $(e, d, n=pq)$:

1. Pick primes $p, q$ such that $n=pq > 127$, compute $n$.
2. Compute totient function $\phi=(p-1)(q-1)$ and pick $e<\phi$ such 
that $e$ and $\phi$ are coprime (i.e. $\gcd(e, \phi)=1$).
3. Pick $d$ such that $de \equiv 1\mod\phi$.
4. Send pair $(e, n)$ to sender.

### Encryption and Decryption

For a given $n$ character long message $s=s_0\ldots s_n$, with characters 
$\{s_i\}$, compute integer character representations $\{m_i\}$ using 
ASCII table below.

![An ASCII character encoding table. By finding the character C that you 
wish to encode the Dec encoding will give a unique integer for that character. 
This can also be used to decode.](images/ascii.png)

Then to encode or decode we simply need the subject, $s$ (either a message 
character integer $m_i$, or a cipher text integer $c_i$), the exponent 
(either $e$ for encyption or $d$ for decryption) and the modulus, $n$, to either 
encrypt a cipher text:
\begin{equation*}
    c_i = m_i^e \mod n,
\end{equation*} 
<div style="display: flex; justify-content: center">
*m* = &nbsp;<input type="text" size=4 id="c1" />, &nbsp;
*e* = &nbsp;<input type="text" size=4 id="d1" />, &nbsp;
*n* = &nbsp; <input type="text" size=4 id="n1" />, &nbsp;
*c* = &nbsp; <span id="m1-calc"/>
</div>
or decrypt a message:
\begin{equation*}
    m_i = c_i^d \mod n,
\end{equation*}
<div style="display: flex; justify-content: center">
*c* = &nbsp;<input type="text" size=4 id="c2" />, &nbsp;
*d* = &nbsp;<input type="text" size=4 id="d2" />, &nbsp;
*n* = &nbsp; <input type="text" size=4 id="n2" />, &nbsp;
*m* = &nbsp; <span id="m2-calc"/>
</div>

## Symmetric Encryption Tools

### Ceasar Cipher

<div>
<input type="radio" id="encrypt" name="mode" value="Encrypt" checked="checked" />
<label for="encrypt">Encrypt</label>
<br />
<input type="radio" id="decrypt" name="mode" value="Decrypt" />
<label for="decrypt">Decrypt</label>
<br />
Shift:
<select id="shift">
    <option value="0">0</option>
    <option value="1">1</option>
    <option value="2" selected="selected">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>
    <option value="6">6</option>
    <option value="7">7</option>
    <option value="8">8</option>
    <option value="9">9</option>
    <option value="10">10</option>
    <option value="11">11</option>
    <option value="12">12</option>
    <option value="13">13</option>
    <option value="14">14</option>
    <option value="15">15</option>
    <option value="16">16</option>
    <option value="17">17</option>
    <option value="18">18</option>
    <option value="19">19</option>
    <option value="20">20</option>
    <option value="21">21</option>
    <option value="22">22</option>
    <option value="23">23</option>
    <option value="24">24</option>
    <option value="25">25</option>
</select>
<br />
<textarea id="input" rows=6 class="fullwidth is_code" spellcheck=false></textarea>
<textarea id="output" rows=6 class="fullwidth is_code" disabled="true" spellcheck=false></textarea>
</div>

### Monoalphabetic Cipher
Use the following tool to encode or decode a monoalphabetic cipher text:
<div id="random" style="display: flex; justify-content: center">
<input type="button" id="random-encode" value="Choose a random encoding" class="italic" />
</div>
<div id="letters" style="display: flex; justify-content: center; flex-wrap: wrap; gap: 15px; margin-bottom: 15px">
<div id="a">A→ <input type="text" id="encode-a" size=1></div>
<div id="b">B→ <input type="text" id="encode-b" size=1></div>
<div id="c">C→ <input type="text" id="encode-c" size=1></div>
<div id="d">D→ <input type="text" id="encode-d" size=1></div>
<div id="e">E→ <input type="text" id="encode-e" size=1></div>
<div id="f">F→ <input type="text" id="encode-f" size=1></div>
<div id="g">G→ <input type="text" id="encode-g" size=1></div>
<div id="h">H→ <input type="text" id="encode-h" size=1></div>
<div id="i">I→ <input type="text" id="encode-i" size=1></div>
<div id="j">J→ <input type="text" id="encode-j" size=1></div>
<div id="k">K→ <input type="text" id="encode-k" size=1></div>
<div id="l">L→ <input type="text" id="encode-l" size=1></div>
<div id="m">M→ <input type="text" id="encode-m" size=1></div>
<div id="n">N→ <input type="text" id="encode-n" size=1></div>
<div id="o">O→ <input type="text" id="encode-o" size=1></div>
<div id="p">P→ <input type="text" id="encode-p" size=1></div>
<div id="q">Q→ <input type="text" id="encode-q" size=1></div>
<div id="r">R→ <input type="text" id="encode-r" size=1></div>
<div id="s">S→ <input type="text" id="encode-s" size=1></div>
<div id="t">T→ <input type="text" id="encode-t" size=1></div>
<div id="u">U→ <input type="text" id="encode-u" size=1></div>
<div id="v">V→ <input type="text" id="encode-v" size=1></div>
<div id="w">W→ <input type="text" id="encode-w" size=1></div>
<div id="x">X→ <input type="text" id="encode-x" size=1></div>
<div id="y">Y→ <input type="text" id="encode-y" size=1></div>
<div id="z">Z→ <input type="text" id="encode-z" size=1></div>
</div>
<div id="encode-remaining"></div>
<textarea id="input-encode" rows=6 class="fullwidth is_code" placeholder="Enter plain text here..." spellcheck=false></textarea>
<textarea id="output-encode" rows=6 class="fullwidth is_code" placeholder="Cipher text will appear here..." disabled="true" spellcheck=false></textarea>

### Vigenère Cipher
Having decided on a key use the techniques you learnt earlier today to encode.

## Breaking RSA
To aid in cracking RSA we have provided you with a tool that computes the
quotient and remainder for two given numbers, i.e. given numbers $n$ and 
$d$ it returns the corresponding $q$ and $r$ from the equation:
\begin{equation*}
    n = q\cdot d + r
\end{equation*}
HINT: This will speed up finding $p$ and $q$ as well as the Euclidean 
algorithm!
<div style="display: flex; justify-content: center">
*n* = &nbsp;<input type="text" size=4 id="nh" />, &nbsp;
*d* = &nbsp;<input type="text" size=4 id="dh" />, &nbsp;
*q* = &nbsp;<span id="qh-calc"></span>, &nbsp;
*r* = &nbsp;<span id="rh-calc"></span>
</div>
