project:
  type: website

website:
  title: "Turing Summer Experience 2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - "computer-vision.qmd"
      - "cryptography.qmd"
      - "language-modelling.qmd"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



