name: publish-website
on:
  push:
    branches:
      - cryptography-web

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: ./cryptography

      - name: Upload rendered files to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cryptography/_book
          publish_branch: gh-pages
          subdir: cryptography
